-- CreateTable
CREATE TABLE "Person" (
    "id" SERIAL NOT NULL,
    "email" TEXT NOT NULL,
    "avatar" TEXT,
    "bio" TEXT,
    "emailprovider" BOOLEAN NOT NULL DEFAULT false,
    "location" TEXT,
    "site" TEXT,
    "timezone" TEXT,
    "utcOffset" INTEGER,
    "nameFamilyName" TEXT,
    "nameGivenName" TEXT,
    "nameFullName" TEXT,
    "employmentDomain" TEXT,
    "employmentName" TEXT,
    "employmentRole" TEXT,
    "employmentSeniority" TEXT,
    "employmentSubRole" TEXT,
    "employmentTitle" TEXT,
    "geoCity" TEXT,
    "geoCountry" TEXT,
    "geoCountryCode" TEXT,
    "geoLat" DOUBLE PRECISION,
    "geoLng" DOUBLE PRECISION,
    "geoState" TEXT,
    "geoStateCode" TEXT,
    "facebookHandle" TEXT,
    "githubId" TEXT,
    "githubHandle" TEXT,
    "githubAvatar" TEXT,
    "githubBlog" TEXT,
    "githubCompany" TEXT,
    "githubFollowers" INTEGER,
    "githubFollowing" INTEGER,
    "googleplusHandle" TEXT,
    "gravatarHandle" TEXT,
    "gravatarAvatar" TEXT[],
    "gravatarAvatars" TEXT[],
    "gravatarUrls" TEXT[],
    "linkedinHandle" TEXT,
    "twitterId" TEXT,
    "twitterHandle" TEXT,
    "twitterAvatar" TEXT,
    "twitterBio" TEXT,
    "twitterFavorites" INTEGER,
    "twitterFollowers" INTEGER,
    "twitterFollowing" INTEGER,
    "twitterLocation" TEXT,
    "twitterSite" TEXT,
    "twitterStatuses" INTEGER,
    "companyId" INTEGER,
    "indexedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Person_pkey" PRIMARY KEY ("id")
);
